spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: UserAccountAPI
          uri: http://127.0.0.1:7072
          predicates:
            - Path=/useraccounts/**
          filters:
            - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:7070/auth/realms/master/protocol/openid-connect/token
            authorization-uri: http://localhost:7070/auth/realms/master/protocol/openid-connect/auth
            userinfo-uri: http://localhost:7070/auth/realms/master/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          keycloak-with-customer-scope:
            provider: keycloak
            client-id: trainee1
            client-secret: 5h5jDxc7YGsbBxhTkufwxhhIxUUait9K
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
          keycloak-without-customer-scope:
            provider: keycloak
            client-id: trainee2
            client-secret: ZenMYu3aPrrwfSsJKp1MJvrrXabryNdO
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
  securitySchemes:
    my_oAuth_security_schema:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://localhost:7070/oauth2/authorize
          scopes:
            read_access: read data
            write_access: modify data

server.port: 7060

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE